---
- name: Change various broker's sysctl-settings
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_broker_config }}'


# to do set naotime to disk mounts

- name: Create kafka directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
  loop:
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"
    - "{{ kafka_conf_dir }}"

- name: Create environment file for Kafka systemd service
  template:
    src: kafka.env.j2
    dest: "{{ kafka_conf_dir }}/kafka.env"
    mode: '0644'

- name: Create kafka service
  template:
    src: kafka.service.j2
    dest: "/etc/systemd/system/kafka.service"
    mode: '0644'

- name: Create  JAAS config file for kafka
  template:
    src: jaas.cfg.j2
    dest: "{{ kafka_conf_dir }}/jaas.cfg"
    mode: '0600'
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'

- name: Create kafka server properties file
  template:
    src: server.properties.j2
    dest: "{{ kafka_conf_dir }}/server.properties"
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: '0644'

- name: Logrotate for kafka logs
  template:
    src: kafka.logrotate.j2
    dest: /etc/logrotate.d/kafka.logrotate
    mode: 0644
    owner: root
    group: root

- name: Enable service kafka and ensure it is not masked
  systemd:
    daemon_reload: yes
    name: kafka
    enabled: yes
    masked: no

- name: Start zookeeper service
  systemd:
    name: kafka
    state: started
    masked: no


- name: set sasl/scram to zookeeper
  command: >
    {{ kafka_install_dir }}/bin/kafka-configs.sh --zookeeper {{ zookeeper_host_scram_generator }} --alter --add-config SCRAM-SHA-256=[password={{ kafka_server_password }}] --entity-type users --entity-name {{ kafka_server_username }}
  run_once: true
  changed_when: false
