---
- name: Pre tasks
  include: pretasks.yml

- name: Configure iptables on hosts
  include: cluster/iptables_cluster.yml
  tags: iptables_cluster

- name: Install monitoring on hosts
  include: cluster/monitoring.yml
  when: monitoring

- name: Install zookeeper on hosts
  include: cluster/install_zookeeper.yml
  when: zookeeper_type is defined

- name: Install kafka on hosts
  include: cluster/install_kafka.yml
  when: zookeeper_type is not defined

#- name: Manage topics
#  include: _manage_topics.yml
#  tags:
#    - manage_topics
