---
- name: Create kafka group
  group:
    name: '{{ kafka_group }}'
    state: present

- name: Create kafka user
  user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    createhome: no

- name: Set kafka_archive_name variable
  set_fact:
    kafka_archive_name: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}"

- name: Unarchive kafka and zookeeper release package
  unarchive:
    src: "{{ kafka_apache_mirror_base_url }}/kafka/{{ kafka_version }}/{{ kafka_archive_name }}.tgz"
    dest: /usr/local
    remote_src: yes
    creates: "/usr/local/{{ kafka_archive_name }}"

- name: Create a link to unarchived destination
  file:
    src: "/usr/local/{{ kafka_archive_name }}"
    dest: '{{ kafka_install_dir }}'
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: link

- name: "Copy additional_monitoring conf files 1"
  template:
    src: "{{ item }}"
    dest: "{{ telegraf_directory }}/telegraf.d/{{ item | basename | regex_replace('.j2','') }}"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - templates/additional_monitoring/*.j2
  notify: Restart service telegraf

- name: "Copy additional_monitoring sh files 1"
  template:
    src: "{{ item }}"
    dest: "{{ telegraf_directory }}/{{ item | basename | regex_replace('.j2','') }}"
    owner: "{{ telegraf_user }}"
    group: "{{ telegraf_group }}"
    mode: 0744
  with_fileglob:
    - templates/additional_monitoring/scripts/*.j2
  notify: Restart service telegraf